// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLN-b9PmJVpFHTL5qdLSR9QG3f8TPfTk',
    appId: '1:360291481822:web:64a1fb98986effcb40aa4f',
    messagingSenderId: '360291481822',
    projectId: 'register-6274b',
    authDomain: 'register-6274b.firebaseapp.com',
    storageBucket: 'register-6274b.appspot.com',
    measurementId: 'G-PB8RTFWW9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tVqih5KypSdJRo3o3J-CgHl4VCl7pSo',
    appId: '1:360291481822:android:99d3d7024daa6bb840aa4f',
    messagingSenderId: '360291481822',
    projectId: 'register-6274b',
    storageBucket: 'register-6274b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-eKwzLQG285w8RT2TFqSH9z2V6Z7FG4',
    appId: '1:360291481822:ios:ccb85d999f3b6ba940aa4f',
    messagingSenderId: '360291481822',
    projectId: 'register-6274b',
    storageBucket: 'register-6274b.appspot.com',
    iosClientId: '360291481822-raco3m4ku9devotrbjj06usqsf5f7jfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs-eKwzLQG285w8RT2TFqSH9z2V6Z7FG4',
    appId: '1:360291481822:ios:ccb85d999f3b6ba940aa4f',
    messagingSenderId: '360291481822',
    projectId: 'register-6274b',
    storageBucket: 'register-6274b.appspot.com',
    iosClientId: '360291481822-raco3m4ku9devotrbjj06usqsf5f7jfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLN-b9PmJVpFHTL5qdLSR9QG3f8TPfTk',
    appId: '1:360291481822:web:1dda8594a9d2d2ef40aa4f',
    messagingSenderId: '360291481822',
    projectId: 'register-6274b',
    authDomain: 'register-6274b.firebaseapp.com',
    storageBucket: 'register-6274b.appspot.com',
    measurementId: 'G-VT4QYBXY2T',
  );
}
